server:
  port: 9001

spring:
  application:
    name: alibaba-payment-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
        # 换成nginx的1111端口，做集群
        # server-addr: 192.168.111.144:1111

