server:
  port: 83

spring:
  profiles:
    active: dev
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: "http://alibaba-payment-service"
